### ISSUE TITLE
Add Sub-Allocate IP Pool to Edge Gateway

### ISSUE THREAD

**Issue by konradinho** [purple-dbu/vmware-vcloud-sdk-php-patched#25]
How to save the Sub-Allocate IP Pool to Edge Gateway?

I would like to set it up like this: http://i.imgur.com/P1M7i90.png

I set Sub-Allocation in this way:

$subAllocationType = new VMware_VCloud_API_SubAllocationType();
$subAllocationType->setEdgeGateway($edgeGatewayRef);      
$subAllocationipRange = new VMware_VCloud_API_IpRangeType();
$subAllocationipRange->setStartAddress('77.79.240.136');
$subAllocationipRange->setEndAddress('77.79.240.136');
$subAllocationipRanges = new VMware_VCloud_API_IpRangesType();
$subAllocationipRanges->setIpRange(array($subAllocationipRange));
$subAllocationType->setIpRanges($subAllocationipRanges);
$subAllocations = new VMware_VCloud_API_SubAllocationsType();
$subAllocations->setSubAllocation($subAllocationType);

**Comment by amercier** [comment]
This project is just about patching the official VMware SDK. For all questions about how to use the SDK, please refet to the [official VMware documentation](http://www.vmware.com/support/pubs/vcd_pubs.html).

However, if this there is a bug is the SDK itself, or if there is a bug in our changes, I'd love to accept a PR :)
